lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false

name: Arseny Razin

sass:
  style: compressed

exclude:
  - "*.less"
  - README.md
  - CNAME
  - Gemfile*
  - Rakefile
  - Vagrantfile
  - vendor
